server {
    listen 80;
    server_name
        xn----7sbbrpmcrj5alb3lrb.xn--p1ai
        www.xn----7sbbrpmcrj5alb3lrb.xn--p1ai
        эстетика-камня.рф
        www.эстетика-камня.рф;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
