# Generated by Django 5.0.5 on 2024-06-22 08:02

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='categories/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to=catalog.models.get_prod_image_path, verbose_name='Изображение')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('damage_resistance', models.TextField(blank=True, null=True, verbose_name='Устойчивость к повреждениям')),
                ('heat_resistance', models.TextField(blank=True, null=True, verbose_name='Термостойкость')),
                ('acid_resistance', models.TextField(blank=True, null=True, verbose_name='Кислотостойкость')),
                ('stain_resistance', models.TextField(blank=True, null=True, verbose_name='Устойчивость к пятнам')),
                ('uv_resistance', models.TextField(blank=True, null=True, verbose_name='УФ устойчивость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Тип материала')),
            ],
        ),
    ]
