# Generated by Django 5.0.5 on 2024-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='acid_resistance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damage_resistance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heat_resistance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stain_resistance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uv_resistance',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
